/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AlgoIcon: typeof import('./components/AlgoIcon.vue')['default']
    AppBar: typeof import('./components/AppBar.vue')['default']
    Goal: typeof import('./components/Goal.vue')['default']
    Node: typeof import('./components/Node.vue')['default']
    NodeIcon: typeof import('./components/NodeIcon.vue')['default']
    Participation: typeof import('./components/Participation.vue')['default']
    Reti: typeof import('./components/Reti.vue')['default']
    Snackbar: typeof import('./components/Snackbar.vue')['default']
  }
}
