/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AlgoIcon: typeof import('./components/AlgoIcon.vue')['default']
    AppBar: typeof import('./components/AppBar.vue')['default']
    Config: typeof import('./components/Config.vue')['default']
    DataDir: typeof import('./components/DataDir.vue')['default']
    Loading: typeof import('./components/Loading.vue')['default']
    Manage: typeof import('./components/Manage.vue')['default']
    Node: typeof import('./components/Node.vue')['default']
    NodeIcon: typeof import('./components/NodeIcon.vue')['default']
    NodeTabs: typeof import('./components/NodeTabs.vue')['default']
    Participation: typeof import('./components/Participation.vue')['default']
    Releases: typeof import('./components/Releases.vue')['default']
    Reti: typeof import('./components/Reti.vue')['default']
    Settings: typeof import('./components/Settings.vue')['default']
    Snackbar: typeof import('./components/Snackbar.vue')['default']
  }
}
