<Project Sdk="Microsoft.NET.Sdk.Worker">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<InvariantGlobalization>true</InvariantGlobalization>
		<PublishAot>true</PublishAot>
		<UserSecretsId>dotnet-ValarService-7e2c9f4a-3b1d-4c8e-9a6f-2d5b8e1c4a7f</UserSecretsId>
		<DebugType Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">none</DebugType>
	</PropertyGroup>

	<ItemGroup>
		<Content Remove="appsettings.Development.json" />
		<Content Remove="appsettings.json" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="10.0.0" />
	</ItemGroup>
</Project>
