#!/bin/sh
# Dedicated least-privilege accounts the node and reti services run as (neither needs root).
create_hidden_user() {
  user="$1"
  realname="$2"
  dscl /Local/Default -read "/Users/${user}" >/dev/null 2>&1 && return 0
  NEW_UID=200
  while dscl /Local/Default -list /Users UniqueID | awk '{print $2}' | grep -q "^${NEW_UID}$"; do
    NEW_UID=$((NEW_UID + 1))
  done
  dscl /Local/Default -create "/Users/${user}"
  dscl /Local/Default -create "/Users/${user}" RealName "${realname}"
  dscl /Local/Default -create "/Users/${user}" UserShell /usr/bin/false
  dscl /Local/Default -create "/Users/${user}" UniqueID "$NEW_UID"
  dscl /Local/Default -create "/Users/${user}" PrimaryGroupID 1
  dscl /Local/Default -create "/Users/${user}" NFSHomeDirectory /var/empty
  dscl /Local/Default -create "/Users/${user}" IsHidden 1
}
create_hidden_user _func-node "FUNC Node"
create_hidden_user _func-reti "FUNC Reti"
mkdir -p /usr/local/share/func
cp /opt/func/Templates/func.api.plist /Library/LaunchDaemons
launchctl bootstrap system /Library/LaunchDaemons/func.api.plist
sleep 2
open http://localhost:3536
exit 0